### ISSUE TITLE
some questions about the localized image editing experiment using Blended Latent Diffusion

### ISSUE THREAD

**Issue by gracezhao1997** [rinongal/textual_inversion#121]
Dear Rinon, 
     I was wondering did you use the CLIP-based loss D_{CLIP} to guide the generation process of stable diffusion in  the localized image editing experiment? If so, since the input of CLIP is in pixel space and the stable diffusion is in latent space, did you first fed the predicted z_0 into the the decoder in stable diffusion to reconstrcut image in pixel space and then fed it to the CLIP model to computeD_{CLIP}(see the figure beblow)? I would be very appreciative if you could reply.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/82632405/203462930-a950cf52-84aa-4c85-b4c7-7de701efa97b.png">

**Comment by rinongal** [comment]
Hi,

We're using [Blended Latent Diffusion](https://arxiv.org/abs/2206.02779). Blended latent diffusion and our paper are based on LDM and not on Stable Diffusion which did not exist at the time. There is no CLIP model involved anywhere in the process, since LDM uses BERT for a text encoder, and the model itself is anyhow already text-conditioned and this can be used to guide the inpainting process.

**Comment by rinongal** [comment]
Closing this since I assume from the e-mails you got your answer. Feel free to re-open if you need additional help.
