### ISSUE TITLE
"String maps to more than a single token" after running main.py a few times

### ISSUE THREAD

**Issue by NathanielAyer** [rinongal/textual_inversion#18]
I was able to run Textual Inversion's main.py successfully a few times today, training on two new concepts (and I cancelled one run between the two successful runs because I had a power outage at home and I disconnected from my instance and wanted a fresh start). The two successful runs didn't seem to be improving after a while and I stopped them with a ctrl-C in the terminal.

However, when I tried running Textual Inversion after that, any --init_word that I entered as an argument and any initializer_words that I tried setting in v1-finetune.yaml resulted in the error "string maps to more than a single token."

I was running Textual Inversion on an AWS EC2 instance running Amazon Linux 2. I tried exiting conda and even rebooted the instance, but continued getting the same error.

**Comment by BIGJUN777** [comment]
Take a look at this issue #9 .

**Comment by rinongal** [comment]
What words did you try? If you're trying things like 'myinitword' or 'myimages' this is not what the init_word is intended for, and these are multi-token inputs. Try a simple, single-word description of your data like 'dog', 'bag', 'face' etc.

**Comment by NathanielAyer** [comment]
@rinongal Thanks for responding to these bug reports. I'm really excited about your work and it's an honor to be talking directly with you.

The words I was trying use were "ikushima" as in Naoki Ikushima and "yoshida" as in Akihiko Yoshida, who are two illustrators I really like. I wanted to teach TI their style by showing it some of their illustrations. But after I started seeing "string maps to more than a single token," I started trying to construct init words that were more and more unique, assuming I needed to find a string that didn't map to anything, and those kept failing. Do you think the error is due to an init word that isn't in the original training data? I tried making some images in SD with prompts like "dancer in the style of yoshida" and got Asian ballerinas instead of ballerinas in Yoshida's style. Do you have any suggestions for an init_word that would be appropriate for an artist's style or work instead of a specific object?

**Comment by rinongal** [comment]
For the style results in the paper I used "painting" as the init_word. It's not too critical so don't spend too much effort optimizing it. Words that are likely to be single-token words are common words that the model saw during training (or that CLIP saw during training, for the case of SD).

If you're looking to train on a specific style, you might also get slightly better results by changing the config files so that the lines which say `ldm.data.personalized.PersonalizedBase` are replaced with `ldm.data.personalized_style.PersonalizedBase`. It basically makes it so that the model trains with sentences of the form "a painting in the style of *" instead of "a photo of *".

**Comment by NathanielAyer** [comment]
Thank you so much! I'm using a more generic word (painting, in this case) and it seems to be working. I also changed personalized to personalized_style and we'll see how that goes.
