### ISSUE TITLE
Analyzing Training

### ISSUE THREAD

**Issue by dboshardy** [rinongal/textual_inversion#34]
First of all, this is incredible work and is a wonder to try out. So thank you! Double-thanks for making such an easy-to-use codebase as well!

Now my question.  What do you look for while training images.  Especially if the given style or subject you're attempting to re-embed has particular details, for instance, a face.  

So far, even going into tens of thousands of global steps, looking at the scaled samples in the log dir, the faces (simple, drawn ones) are still masses of semi-legible squiggly lines that only offer a face via pareidolia.

A follow-on question is, how do you/should we use the several different output images in determining whether to stop training?

**Comment by rinongal** [comment]
Thank you! The codebase is mostly LDM, so the thanks there should likely go to the CompVIS team :)

On training for faces: We did not try any faces ourselves, but you're likely to have a fairly bad time with the LDM version if you're trying to learn a specific face. The method doesn't really preserve identity. 
If you look at the cat examples in our paper, for example, you'll see that it retains high-level details like the overall shape of the sculpture and the fact that it has vertical rainbow lines, but it does not preserve their actual color arrangement.

If you're using SD - you might be able to get a better fit if you just increase the learning rate or the number of vectors the model assigns to the tokens (both in the config), but this will make re-using the concepts in future prompts harder. We're trying to improve things, but SD is being stubborn and it looks like our hope that the swap will just be a matter of parameter tuning isn't panning out :)

I wouldn't go into the tens of thousands of iterations, there's unlikely to be a change at that point. Your time is better spent on playing with the above parameters instead. You can also look [here](https://www.reddit.com/r/StableDiffusion/comments/wz88lg/i_got_stable_diffusion_to_generate_competentish/) and see if their suggestions help your case as well.

On the question of how to use the outputs to understand what's going on:
1) The inputs_gs images are good for a sanity check. Make sure the inputs are what you expect (i.e. no unexpected cropping, the images aren't rotated 90 degrees due to file metadata etc.).
2) The reconstruction_gs images can be used to check if the details you're missing are actually retained by the model's encoding step. Some fine details don't survive the encoding-decoding process, and you won't be able to 'learn' them.
3) The samples_scaled images are the training output you really care about. Here I'd try to make sure that: (1) The images are improving as training proceeds. (2) They are converging towards something that resembles the input set. When picking a checkpoint to use, you generally want the earliest one where results are 'good enough' for you.

There's not much more to it than that :shrug:

**Comment by dboshardy** [comment]
Thank you for your prompt and informative response!  

I tried to grep the code base to find "samples_scaled" to see what is being used to generate those images but couldn't find anything.  What prompts are used to generate the "samples" and "samples_scaled" outputs?

**Comment by rinongal** [comment]
They are both generated in the log_images method (in ddpm.py).

You can find the prompts in the conditioning_gs image in the same output directory. These are random prompts from the list in ldm/data/personalized.py (the same list used for training).

The difference between samples and samples_scaled is that the first is using a classifier-free guidance scale of 1.0 (which produces mostly noise), while the later is using 5.0.

**Comment by dboshardy** [comment]
Thanks again!
