### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by rickyars** [rinongal/textual_inversion#41]
I get this error after 500 iterations when it attempts to print out the sample/test images of the checkpoint. I think it has to do with the image that's dumped which contains nothing but the prompt text. (1) Is there an easy fix? (2) Is there a better way to log the prompt instead of dumping a mostly white image?

**Comment by rinongal** [comment]
Are you using windows? If so, it might be a missing font problem (see e.g. #12). I've also seen other solutions floating around on reddit. But really, you can probably just disable these images in log_images in ddpm.py (comment out the entire block starting with `if self.model.conditioning_key is not None:`)

Regarding other ways to log them - this is part of the original LDM code, and I saw no reason to change it since it worked for me :) You're free to change it if you want, but I'm not sure it's worth the effort.

**Comment by rickyars** [comment]
thanks for the quick reply. i'm running on Google Colab.

**Comment by rickyars** [comment]
@rinongal looks like all you need to do is change `textual_inversion/ldm/util.py`, line 25 
from:
```
font = ImageFont.truetype('data/DejaVuSans.ttf', size=size)
```
to:
```
font = ImageFont.load_default()
```

**Comment by rinongal** [comment]
Cheers. I'll update it in the next revision. May as well make sure it works on more environments :shrug:

**Comment by ghpkishore** [comment]
You can also add the DejaVuSans.tff into the data folder of ldm and change this `font = ImageFont.truetype('data/DejaVuSans.ttf', size=size)` to `font = ImageFont.truetype('Full PATH to the file/DejaVuSans.ttf', size=size)` in the util.py in ldm folder. That also takes care of this error

**Comment by rinongal** [comment]
Closing this since it seems to be resolved.
