### ISSUE TITLE
Inpainting only accepts image and mask

### ISSUE THREAD

**Issue by dboshardy** [rinongal/textual_inversion#46]
I've seen in other instances of inpainting tasks, that it takes a prompt to guide the inpainting.  Looking at `scripts/inpaint.py` there is no prompt taken.  There is only the image and mask (per image in `indir`).  And since the inverted embeddings are guided via the text prompt and their custom token, how do we pass that information to the inpainting?  

I also see there is nowhere in `scripts/inpaint.py` to load any custom fine-tuned embeddings.

**Comment by dboshardy** [comment]
I'm gathering the inpainting script is from the original ldm repo.  Will you upload code samples of inpainting guided by image and/or text at some point?

**Comment by rinongal** [comment]
The inpainting script is indeed from the original LDM repo. The inpainting examples from our paper used [Blended Latent Diffusion](https://arxiv.org/abs/2206.02779), but their code isn't publicly released yet. They were nice enough to give us an early 'sneak peak'.

If their code becomes public in a reasonable time-frame I'll probably add support to this repo. Otherwise, we have no plans to add in-painting.
