### ISSUE TITLE
Per image tokens on a larger dataset

### ISSUE THREAD

**Issue by LexCybermac** [rinongal/textual_inversion#47]
I'm curious about trying per-image token training with my dataset however the per_img_token_list in personalized.py is only 22 entries long, which appears to be posing an issue in that there aren't enough of those tokens to assign to samples in my set.

I have considered manually supplementing the list by hand which would be an incredibly tedious but perhaps doable task on account of the fact that the set I'm wanting to train with only has 912 samples, but other datasets I was interested in experimenting with have past half a million samples for which a manual approach simply wouldn't suffice. Is there any possibility of generating unique multi-character tokens on the fly when starting training to an extent varying depending on dataset size?

**Comment by rinongal** [comment]
The code is currently implemented by relying on tokens that already exist in the text-encoder. These are limited to begin with (roughly 320k in the case of LDM, and probably a similar amount in SD - including all the real words that you want to keep using as before), so there's not enough tokens to support a half-a-million image set.

That said, this restriction is simply due to ease of implementation with our current approach.
If you're really inclined to do this, you could re-implement the tokenization / embedding logic in order to support entirely new tokens, and in that case you'd be able to just generate them on-the-fly as you wish.

Either way, I'm not sure there's much benefit to pursuing this path. The per-image token approach wasn't too helpful in most of our experiments.

**Comment by LexCybermac** [comment]
Duly noted, thanks for your advice :D
