### ISSUE TITLE
Possible to find the closest actual word in the dictionary?

### ISSUE THREAD

**Issue by isikdogan** [rinongal/textual_inversion#53]
Is it possible to find the closest existing word to the learned embedding instead of adding a new token to the dictionary?
It would be interesting to try those words in black-box image generators, like DALL-E, and see if it still means the same thing.

**Comment by rinongal** [comment]
I can interpret this question in two ways, so I'll try to answer both:

1) Can we determine what words were closest to the embedding we learned? The answer here is yes, but those words are generally gibberish. At least for LDM, I did not re-try the experiment with SD. I don't think there'll be any meaning to inserting them into DALL-E2, our embeddings are generally far out-of-domain compared to regular words.

2) Can we optimize for a set of words that describe the subject, instead of optimizing for a new embedding vector? The answer here is also mostly yes, you can see what advadnoun is doing [here](https://twitter.com/Ted_Underwood/status/1563005610362564610). I'm not sure how well it generalizes to arbitrary concepts though.

**Comment by isikdogan** [comment]
Thanks! My question was the first one but the second one is an interesting question too.
