### ISSUE TITLE
Project page uses artwork of an artist who recently passed away

### ISSUE THREAD

**Issue by yesokcool** [rinongal/textual_inversion#56]
The project page uses art by the artist Qinni, who recently passed away in 2020.

I know that their art is available for non-commercial use, but I believe it is in poor taste to use her art as an example for this project.

This was discussed on [the most recent episode of the podcast Cortex](https://www.relay.fm/cortex/133).

**Comment by rinongal** [comment]
I am a personal fan of Qinni's art, and even have a print of one of her deviations on my wall. 
When I looked for artists to experiment with, her work was the first thing that sprang to mind. To me this was an opportunity to pay tribute to her work and hopefully expose it to a few more people.

In our paper and [project page](https://textual-inversion.github.io/) we do directly link to her page, though I see this was omitted in this repository and I'll amend this to give her proper credit here as well.

Finally, if you do have any concrete reasons to believe that this use goes against her **explicit** wishes, you're welcome to list them and I'll consider replacing her examples. 

If this is just a matter of the medium (AI art vs. hand-drawn tributes), then I respect your opinion on the subject, but I do not see a compelling reason why it should overwrite my own.

**Comment by yesokcool** [comment]
Mentioning the personal connection to the artist and that your intentions are to tribute the artist’s work may be worth mentioning to clarify intentions - perhaps as an addendum placed at the end of the paper.

Here are my concerns to consider why using her art may be seen negatively, especially without clarification of intentions:

1. The recency of her passing makes this a much more sensitive matter in general. It comes across as unsettling. I realize this is subjective though.
2. There is no mention of any outreach to or verbal permission granted by the current individual managing their art.
3. The permission granted by the artist is an informal “non-commercial use,” which very likely did not imply AI usage at the time the artist was alive, as the technology wasn’t nearly as widespread as it is now. This leaves the artist’s consent as dubious. Explicit consent is impossible.
4. The choice to use and mimic the works of an artist who recently died, over any other living artist who *can* be explicitly asked for permission, or a historical artist whose death is less recent, can come across as needlessly disrespectful and tone deaf. It comes across as unnecessarily jumping the gun to the most extreme-case scenario of what's possible rather than a tribute.

It’s ultimately your decision and I understand both sides of the issue. The opinion of mine does not override yours, but I think it's an important matter to consider.

**Comment by rinongal** [comment]
Using living artists is its own can of worms. While you are correct that they can give permission, they can also be directly and financially impacted by someone mimicking their style. In fact, before publication I had discussions with artists who specifically highlighted the impact of such methods on still living artists, and implored me to consider using deceased individuals.
In other words: the moral advantage of using living individuals is not all that clear.

I can understand the argument for historical artists - but the model already knows their work. In that sense, they do not serve as an example of an ability to learn new styles. This is a fundamental requirement of the academic work. If I make a claim, I need to back it up with evidence, and showing that I can mimic Picasso provides no such evidence.

And really, beyond all of this, Qinni's work has been replicated as a tribute hundreds if not thousands of times by artists, including as early as weeks after her death. For example: [1](https://mymodernmet.com/qinni-tribute-art/), [2](https://mashable.com/article/qinni-qing-han-artist-died), [3](https://www.youtube.com/watch?v=3_oraSFkt9s&ab_channel=Flasho-D), [4](https://www.youtube.com/watch?v=ZcnjLzoDSlY&ab_channel=cin_ah) and many many more. You can see the reactions to those videos and articles yourself. There is no outrage over the use of her style. 

Why is this case different? Because I do not have the skill to draw such paintings myself, and instead used a program that _I created_ to do it? The sarcastic side in me can't help but ask: is the "outrage" in that podcast really due to the use of Qinni's work, or is it because they are looking for yet another excuse to bash AI art?

**Comment by yesokcool** [comment]
Those are all fair points. 

I think what my main point boils down to is that acknowledgement of the artist’s passing and clarification of your intentions may be warranted to avoid further misunderstanding. I’ll elaborate further though.

Firstly, I’d just like to note that there are likely thousands of small artists you can find, especially those who are not financially independent, who would welcome the exposure. I can’t say if choosing one of them and using their art is the clear decision to make though.

I wouldn’t describe the podcast's discussion as outrage - it's more a general sense of unease, especially because they were unsure whether the creators knew about the artist's passing or not. I had the same sort of feeling upon hearing about it. The natural response, from how I’ve seen people react to this, is that it seems strange that this artist's work was chosen in particular out of all other choices. It's not necessarily something that most people are going to care about or notice, but this reaction has been exemplified in the podcast hosts, myself, and a few close relatives upon noticing this.

The tributes made by people is art solely created as a tribute, whereas the context established in this project is art created as a "showcase" of what a new technology can do. It’s not creating a standalone gallery saying "I created this program specifically to make this art as a tribute to this artist,” it’s instead a paper saying "I created this program that can mimic anything you give it, here’s an example of it using and mimicking the art of someone who recently passed away.” That wording is obviously not fair, but that is the sentiment that comes across when seeing the art in the paper without the further context you have given here. 

AI-created art is already viewed as a somewhat soulless way to create art and as potentially threatening to the livelihoods of many artists, and the framing of “look what this can do” while using their art, without any mention of their recent death, only further emphasizes the lack of compassion for people and artists, even if it’s not the intention at all. This view on AI art can just be a knee-jerk reaction to new technology that will change over time, but using her art like this certainly does not help improve the case of AI art in the public eye.

It’s like creating a humanoid robot that can imitate anyone’s mannerisms, and then choosing someone who recently died as an example to imitate. It’s dealing with a fresh, sensitive matter, while also using the personal, unique expression of a human being without their explicit consent, with an implied purpose of being their replacement. it’s not objectively wrong, it’s just unsettling.

I can’t say if it’s necessary to replace her work in the paper entirely. A possible showing of goodwill, however, could be to acknowledge her passing or clarify your intentions to pay tribute somewhere in the project, so your intentions are not misconstrued in the worst possible way: as coldly and purposefully selecting this artist to exemplify how their existence is no longer needed or valued. It’s obvious this is not your intention, and I don’t think there has been any wrongdoing - it’s just a strange new context where things like this should be discussed.
