### ISSUE TITLE
How did you prepare the prompts when training the Sstyle?

### ISSUE THREAD

**Issue by ajundo** [rinongal/textual_inversion#81]
Thanks for the great job!
I modified the `./ldm/data/personalized.py` file, simply replacing all the 'of' by 'in the style of'. I'm not sure if it's correct.

**Comment by GucciFlipFlops1917** [comment]
You'll have better luck starting with the style variant of personalized.py ([personalized_style.py](https://github.com/rinongal/textual_inversion/blob/main/ldm/data/personalized_style.py)) and referencing the respective yaml config before running. It's already pre-configured for that purpose.

**Comment by rinongal** [comment]
As @GucciFlipFlops1917 noted, you can use personalized_style.py. If you're using LDM, you can just use [txt2img-1p4B-finetune_style.yaml](https://github.com/rinongal/textual_inversion/blob/main/configs/latent-diffusion/txt2img-1p4B-finetune_style.yaml). Otherwise you can just change the targets in the data block of the yaml to ``target: ldm.data.personalized_style.PersonalizedBase``.
