### ISSUE TITLE
What is init_word?

### ISSUE THREAD

**Issue by EKZERSIS** [rinongal/textual_inversion#88]
Why do we need to use --init_word in train if we have --placeholder_tokens ?

What kind of init_word exists?
How will the geniracy result change if you specify a different init_word?

**Comment by CodeExplode** [comment]
Placeholder_token is what you'd use in your prompt to activate your embedding.

e.g. A photo of *

* would be your placeholder token. In indicates to the code that you want to get the embedding from your saved file, rather than look up an embedding from the in-built dictionary. Some newer implementations have done away with tokens, e.g. automatic1111's UI for stable diffusion will use the filename of the embedding, so you could say "A photo of JohnSmith" and have a file called JohnSmith.pt in your embeddings directory.

init_word is the word you want to copy the embedding of to start the process. e.g. If you're trying to build a new embedding for a man, you might start with 'man' as your initial word to copy the embedding of, and then the process will try to change that embedding to match your new examples.

**Comment by rinongal** [comment]
@CodeExplode pretty much summed it up :) Thanks!

**Comment by rinongal** [comment]
Closing this since the question was answered. Feel free to reopen if you need more help.
